[package]
name = "leafrog"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.7", default-features = false, features = [
    "bevy_gilrs",
    "bevy_winit",
    "render",
    "png",
    "x11",
] }
iyes_loopless = { version = "0.5", features = ["states"] }
iyes_progress = { version = "0.3", features = ["iyes_loopless", "assets"] }
leafwing-input-manager = "0.3"
bevy-inspector-egui = "0.11"
bevy_tweening = "0.4"
heron = { version = "3.0", features = ["2d"] }
# heron_debug = { version = "3.1", features = ["2d"] }
bevy_kira_audio = "0.10"
fastrand = "1.7"
